version: '3.8'

services:
  records-manager:
    image: nordz0r/records-manager:latest
    container_name: records-manager
    volumes:
      - /etc/asterisk/local/extensions.conf:/app/extensions.conf
      - /home:/app/home
    ports:
      - "80:8080"
    restart: always